<?php

/**
 * Help Center article metadata for server-side features (sitemap, SEO head, JSON-LD).
 * Keep in sync with resources/js/constants/help.js.
 * Generated by scripts/generate-help-content.mjs
 * Or sync SEO fields only: node scripts/sync-seo-php-from-js.mjs
 */
return [

    'articles' => [
        [
            'slug' => 'what-is-cubsign',
            'updated_at' => '2026-08-08',
            'title' => 'What Is CubSign?',
            'excerpt' => 'CubSign is a browser-based PDF signing tool: upload a PDF, place fields, sign yourself or send for signature, and download the finished file.',
            'meta_title' => 'What Is CubSign? Online PDF Signing Explained | CubSign',
            'meta_description' => 'Learn what CubSign does today: PDF-only uploads, guest self-sign, draw/type/upload signatures, workspace storage, templates, and send-for-signature links.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'Is CubSign free to use?',
                'answer' => 'Yes. CubSign is free during Early Access. You can upload, sign, and send PDFs without a credit card.',
            ],
            [
                'question' => 'Do I need to install anything?',
                'answer' => 'No. CubSign runs in a modern web browser on desktop and mobile. There is no app or plugin to install.',
            ],
            [
                'question' => 'Can I sign without an account?',
                'answer' => 'Yes, for one guest self-sign session. After that, create a free account to keep signing, store documents, use templates, and send PDFs to others.',
            ],
        ],
        ],
        [
            'slug' => 'create-your-cubsign-account',
            'updated_at' => '2026-08-08',
            'title' => 'Create Your CubSign Account',
            'excerpt' => 'Create a free CubSign account to store documents, use templates, and send PDFs for signature after your one guest self-sign session.',
            'meta_title' => 'Create Your CubSign Account (Free) | CubSign',
            'meta_description' => 'Register with email or Google to unlock CubSign workspace storage, templates, send-for-signature, and email verification for full access.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'Does creating an account cost anything?',
                'answer' => 'No. Registration is free during Early Access, and no credit card is required.',
            ],
            [
                'question' => 'Can I register with Google?',
                'answer' => 'Yes. Choose Continue with Google to sign in without a separate CubSign password. See the Google Login article.',
            ],
            [
                'question' => 'What if I already signed as a guest?',
                'answer' => 'Guest sessions are not tied to an account and are limited to one self-sign flow. Create an account to continue signing and to save documents in your workspace.',
            ],
        ],
        ],
        [
            'slug' => 'mobile-support',
            'updated_at' => '2026-08-11',
            'title' => 'Mobile Support',
            'excerpt' => 'Sign PDFs on phones and tablets in Safari or Chrome — no app install, with practical tips for touch signing and uploads.',
            'meta_title' => 'Mobile Support: Sign PDFs on Your Phone | CubSign',
            'meta_description' => 'Learn how to upload and sign PDFs on phones and tablets with CubSign, plus tips for signatures, uploads, and downloads on small screens.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'Do I need an app to sign on mobile?',
                'answer' => 'No. Open cubsign.com in Safari (iOS) or Chrome (Android). CubSign is a web app, not a native app.',
            ],
            [
                'question' => 'Why does signing fail inside my email app?',
                'answer' => 'In-app browsers often block uploads or downloads. Tap Open in Safari or Open in Chrome and retry.',
            ],
            [
                'question' => 'Draw or type on a phone?',
                'answer' => 'Both work. Landscape helps when drawing; typed signatures are often cleaner on small screens.',
            ],
        ],
        ],
        [
            'slug' => 'browser-compatibility',
            'updated_at' => '2026-08-08',
            'title' => 'Browser Compatibility',
            'excerpt' => 'See which browsers CubSign supports and how to fix a signing editor that looks broken.',
            'meta_title' => 'Supported Browsers for CubSign | CubSign',
            'meta_description' => 'Find out which browsers CubSign supports for uploading, signing, and downloading PDFs, plus fixes for a broken editor.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'Which browser works best with CubSign?',
                'answer' => 'Any current version of Chrome, Firefox, Edge, or Safari works well. Keeping the browser updated prevents most editor and upload issues.',
            ],
            [
                'question' => 'Why is the signing editor blank?',
                'answer' => 'A blank editor usually means an outdated browser, a blocking extension, or stale cached assets. Refresh, update, disable extensions, or clear the cache.',
            ],
            [
                'question' => 'Is Internet Explorer supported?',
                'answer' => 'No. Internet Explorer is not supported. Please use a modern browser such as Chrome, Firefox, Edge, or Safari.',
            ],
        ],
        ],
        [
            'slug' => 'how-to-upload-a-pdf',
            'updated_at' => '2026-08-08',
            'title' => 'How to Upload a PDF',
            'excerpt' => 'Upload a PDF up to 25 MB from desktop or mobile and open the CubSign signing editor.',
            'meta_title' => 'How to Upload a PDF to CubSign | CubSign',
            'meta_description' => 'A clear, step-by-step guide to uploading a PDF to CubSign from desktop or mobile, plus tips to avoid failed uploads.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'How do I upload a PDF?',
                'answer' => 'Open the Upload PDF page, drag your file onto the drop zone or click to browse, and wait for the editor to open.',
            ],
            [
                'question' => 'Can I upload from my phone?',
                'answer' => 'Yes. Tap the upload area and pick a PDF from Files, Photos, or cloud storage. Use a stable connection for larger files.',
            ],
            [
                'question' => 'What if upload keeps failing?',
                'answer' => 'Confirm the file is a real PDF under 25 MB and not password-protected. See Troubleshooting Upload Errors.',
            ],
        ],
        ],
        [
            'slug' => 'supported-file-types',
            'updated_at' => '2026-08-08',
            'title' => 'Supported File Types',
            'excerpt' => 'CubSign accepts PDF documents only. Convert Word, Excel, or images to PDF before uploading.',
            'meta_title' => 'Supported File Types for Uploads | CubSign',
            'meta_description' => 'Understand which file types CubSign accepts for signing, why PDF is required, and how to convert Word, Excel, and images to PDF.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'What file types can I upload?',
                'answer' => 'PDF (.pdf) only, up to 25 MB. Convert other formats before uploading.',
            ],
            [
                'question' => 'Can I upload Word?',
                'answer' => 'Not directly. Use Save as PDF or Export to PDF in Word, then upload the result.',
            ],
            [
                'question' => 'Can I upload an image as the document?',
                'answer' => 'No for the main document. You can upload PNG or JPG when creating a signature image — see Upload Your Signature Image.',
            ],
        ],
        ],
        [
            'slug' => 'maximum-upload-size',
            'updated_at' => '2026-08-08',
            'title' => 'Maximum Upload Size',
            'excerpt' => 'CubSign accepts PDF uploads up to 25 MB. Here is how to shrink files that exceed the limit.',
            'meta_title' => 'Maximum PDF Upload Size (25 MB) | CubSign',
            'meta_description' => 'Learn about the 25 MB CubSign upload limit and practical ways to compress or split large PDFs so they upload successfully.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'What is the maximum upload size?',
                'answer' => '25 MB per PDF. Most contracts and forms are much smaller.',
            ],
            [
                'question' => 'How do I reduce file size?',
                'answer' => 'Compress the PDF, lower scan DPI (150–200 is usually enough), remove oversized embedded images, or split into separate files when the workflow allows.',
            ],
            [
                'question' => 'Upload failed but the file is small?',
                'answer' => 'Network drops, VPNs, browser extensions, or password-protected PDFs can cause failures unrelated to size. See Troubleshooting Upload Errors.',
            ],
        ],
        ],
        [
            'slug' => 'how-to-sign-a-pdf-online',
            'updated_at' => '2026-08-11',
            'title' => 'How to Sign a PDF Online',
            'excerpt' => 'Upload a PDF, place fields, create your signature, and download the signed file — or send it to others for signature.',
            'meta_title' => 'How to Sign a PDF in CubSign | CubSign',
            'meta_description' => 'Learn how to sign a PDF in CubSign: upload your document, add your signature, place it on the page, and download the signed file.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'Do I need an account?',
                'answer' => 'No for your first guest self-sign session. A free account is required to continue signing afterward and to send documents to others.',
            ],
            [
                'question' => 'How long does signing take?',
                'answer' => 'A simple one-signature PDF often takes under a minute once you are familiar with the editor.',
            ],
            [
                'question' => 'Can I sign on my phone?',
                'answer' => 'Yes. See Mobile Support for touch and browser tips.',
            ],
        ],
        ],
        [
            'slug' => 'draw-vs-type-signature',
            'updated_at' => '2026-08-08',
            'title' => 'Draw vs Type Signature',
            'excerpt' => 'Compare drawing and typing your signature so you can pick the best option for each document.',
            'meta_title' => 'Draw vs Type Signature: Which to Use | CubSign',
            'meta_description' => 'Compare drawing and typing your electronic signature in CubSign, including when each option looks and works best.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'Is a drawn signature more legal than a typed one?',
                'answer' => 'No. Both drawn and typed signatures are valid electronic signatures when you intend to sign. The method is a matter of appearance and comfort.',
            ],
            [
                'question' => 'Which should I use on my phone?',
                'answer' => 'Drawing works well in landscape, but typing is often cleaner on small screens. Try both and keep whichever reads best.',
            ],
            [
                'question' => 'Can I use an existing signature image instead?',
                'answer' => 'Yes. If you already have a signature PNG or JPG, see Upload Your Signature Image to use it directly.',
            ],
        ],
        ],
        [
            'slug' => 'upload-your-signature-image',
            'updated_at' => '2026-08-08',
            'title' => 'Upload Your Signature Image',
            'excerpt' => 'Use an existing signature PNG or JPG instead of drawing or typing, and place it on your PDF.',
            'meta_title' => 'Upload Your Signature Image | CubSign',
            'meta_description' => 'Learn how to upload a signature PNG or JPG in CubSign and place it cleanly on your PDF, with image quality and privacy tips.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'What format works best?',
                'answer' => 'PNG with a transparent background is ideal. A high-contrast, tightly cropped JPG also works.',
            ],
            [
                'question' => 'Why does my signature look boxed in?',
                'answer' => 'The image likely has a solid background. Use transparency or crop tightly around the ink.',
            ],
            [
                'question' => 'Is my image saved forever in CubSign?',
                'answer' => 'It is used in your current signing session. CubSign does not offer a persistent signature library across all future documents.',
            ],
        ],
        ],
        [
            'slug' => 'download-signed-pdf',
            'updated_at' => '2026-08-08',
            'title' => 'Download Signed PDF',
            'excerpt' => 'Save the final signed PDF to your device after completing a signature, and find it later in your workspace.',
            'meta_title' => 'How to Download a Signed PDF | CubSign',
            'meta_description' => 'Learn how to download your signed PDF after signing, retrieve it from your workspace, and understand what the file contains.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'How do I download after signing?',
                'answer' => 'Complete all fields, finish the flow, and click Download on the completion screen.',
            ],
            [
                'question' => 'Can I download later?',
                'answer' => 'Signed-in users can download again from Documents in the workspace. Guests must download during the session — there is no saved copy afterward.',
            ],
            [
                'question' => 'What is in the file?',
                'answer' => 'The PDF with applied signatures and field values from the session. Activity events are tracked separately in your workspace — see Audit Trail.',
            ],
        ],
        ],
        [
            'slug' => 'share-documents',
            'updated_at' => '2026-08-08',
            'title' => 'Share Documents',
            'excerpt' => 'Send a PDF for signature by email. Recipients sign at a unique /r/{token} link without a CubSign account.',
            'meta_title' => 'How to Share Documents for Signature | CubSign',
            'meta_description' => 'Learn how to send a PDF for signature with CubSign, assign recipients, and track completion. Recipients sign from a secure link.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'Do recipients need an account?',
                'answer' => 'No. They open the email link, review the PDF, and sign at /r/{token}.',
            ],
            [
                'question' => 'How do I track progress?',
                'answer' => 'Check document status and activity in your workspace. You receive notifications as recipients complete their fields.',
            ],
            [
                'question' => 'Multiple signers?',
                'answer' => 'Add a field for each person, assign fields to the correct recipient email, and send once.',
            ],
        ],
        ],
        [
            'slug' => 'delete-documents',
            'updated_at' => '2026-08-08',
            'title' => 'Delete Documents',
            'excerpt' => 'Remove documents from your CubSign workspace when you no longer need them, safely and deliberately.',
            'meta_title' => 'How to Delete Documents in CubSign | CubSign',
            'meta_description' => 'Learn how to delete documents from your CubSign workspace, what deletion means, and what to check before you remove a file.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'How do I delete a document in CubSign?',
                'answer' => 'Sign in, open Documents, find the file, open its actions, choose Delete, and confirm. You can Archive instead for a softer cleanup.',
            ],
            [
                'question' => 'Can I recover a deleted document?',
                'answer' => 'Treat deletion as permanent. Download a final signed copy before deleting, and use Archive if you might need the file later.',
            ],
            [
                'question' => 'What happens to recipients if I delete a shared document?',
                'answer' => 'If a signing request was already sent, recipients may lose access once the document is deleted. Confirm no active request depends on it first.',
            ],
        ],
        ],
        [
            'slug' => 'email-verification',
            'updated_at' => '2026-08-08',
            'title' => 'Email Verification',
            'excerpt' => 'Verify your email address to unlock the full CubSign workspace and receive signing notifications.',
            'meta_title' => 'Email Verification in CubSign | CubSign',
            'meta_description' => 'Learn how CubSign email verification works, why it matters, and what to do if the verification email does not arrive.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'Why does CubSign need to verify my email?',
                'answer' => 'Verification confirms account ownership, enables signing notifications, and prevents someone else from creating an account with your address.',
            ],
            [
                'question' => 'The verification email never arrived, what do I do?',
                'answer' => 'Check spam and promotions folders, confirm you typed the address correctly, and request a new verification email. Allowlist cubsign.com if your provider filters unknown senders.',
            ],
            [
                'question' => 'Do Google Login users need to verify email?',
                'answer' => 'Generally no. Google Login authenticates through Google, so a separate verification step is typically unnecessary.',
            ],
        ],
        ],
        [
            'slug' => 'google-login',
            'updated_at' => '2026-08-08',
            'title' => 'Google Login',
            'excerpt' => 'Sign in to CubSign quickly and securely with your Google account, with no separate password to manage.',
            'meta_title' => 'Sign In with Google Login | CubSign',
            'meta_description' => 'Learn how to use Google Login with CubSign, what data CubSign receives, and how to switch between Google and email sign-in.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'Does Google Login give CubSign access to my Gmail or Drive?',
                'answer' => 'No. CubSign uses Google only for authentication basics like your name and email. It does not access your Gmail content or Drive files.',
            ],
            [
                'question' => 'Can I switch from email login to Google Login?',
                'answer' => 'Use the same email consistently. If you registered with email and password, contact support before linking a Google account to avoid duplicate profiles.',
            ],
            [
                'question' => 'What if I forget which Google account I used?',
                'answer' => 'Try the addresses you commonly use. If you still cannot access your account, reach out from the Contact page for help.',
            ],
        ],
        ],
        [
            'slug' => 'reset-password',
            'updated_at' => '2026-08-08',
            'title' => 'Reset Password',
            'excerpt' => 'Recover access to your CubSign account if you forgot your password, using a secure reset link.',
            'meta_title' => 'How to Reset Your Password | CubSign',
            'meta_description' => 'Step-by-step guide to resetting your CubSign password with a secure link, plus password tips and the Google Login alternative.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'How do I reset my CubSign password?',
                'answer' => 'On the Login page choose Forgot password, enter your email, open the reset email, click the secure link, and set a new password.',
            ],
            [
                'question' => 'The reset link stopped working, why?',
                'answer' => 'Reset links expire for security. Request a new link from the Forgot password prompt and use it promptly.',
            ],
            [
                'question' => 'I use Google Login, do I need a password?',
                'answer' => 'No. Google Login users do not need a CubSign password. Just choose Continue with Google on the login page.',
            ],
        ],
        ],
        [
            'slug' => 'secure-storage',
            'updated_at' => '2026-08-08',
            'title' => 'Secure Storage',
            'excerpt' => 'How CubSign protects PDFs in transit with HTTPS and limits access to stored files — without overstating encryption claims.',
            'meta_title' => 'Secure Storage: How CubSign Protects Documents | CubSign',
            'meta_description' => 'CubSign uses HTTPS for uploads and signing, stores PDFs on private infrastructure with access controls, and hashes passwords. Learn what we do and do not claim.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'Is my PDF encrypted in transit?',
                'answer' => 'Yes. Connections to CubSign use HTTPS (TLS), including uploads, signing sessions, and downloads.',
            ],
            [
                'question' => 'Does CubSign use AES-256 encryption at rest?',
                'answer' => 'We do not claim AES-256 or bank-level encryption at rest. PDFs are stored on private server storage with access controls limited to authorized account holders and valid signing links.',
            ],
            [
                'question' => 'What can I do on my side?',
                'answer' => 'Use a strong unique password or Google Login, verify recipient emails, avoid shared public computers, and delete documents you no longer need.',
            ],
        ],
        ],
        [
            'slug' => 'document-privacy',
            'updated_at' => '2026-08-08',
            'title' => 'Document Privacy',
            'excerpt' => 'Who can see your documents and how CubSign keeps uploaded files private by default.',
            'meta_title' => 'Document Privacy in CubSign | CubSign',
            'meta_description' => 'Understand how CubSign keeps documents private, who can access them, what staff can see, and how to control your own privacy.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'Are documents public?',
                'answer' => 'No. Documents are private by default — not listed in search engines. Only you and invited recipients with valid links can access them.',
            ],
            [
                'question' => 'Can CubSign staff read my PDFs?',
                'answer' => 'Staff access is limited to legitimate support needs you initiate. We do not sell document contents or use them for advertising.',
            ],
            [
                'question' => 'How do I reduce exposure?',
                'answer' => 'Share narrowly, verify emails, download what you need, and delete finished documents from your workspace.',
            ],
        ],
        ],
        [
            'slug' => 'audit-trail',
            'updated_at' => '2026-08-08',
            'title' => 'Audit Trail',
            'excerpt' => 'CubSign logs signing events in your workspace — sent, notified, signed, completed, and generation failures — not page views or IP addresses in the UI.',
            'meta_title' => 'What Is an Audit Trail in CubSign? | CubSign',
            'meta_description' => 'See which DocumentActivity events CubSign records: recipient_notified, recipient_signed, document_completed, signed_pdf_failed — and where to find them.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'What events does CubSign record?',
                'answer' => 'Events include document creation, send preparation, recipient_notified, recipient_signed, document_completed, and signed_pdf_failed when PDF generation fails. View/open events are not logged in this timeline.',
            ],
            [
                'question' => 'Where do I see activity?',
                'answer' => 'Open a document in your workspace to view its activity timeline. Keep downloaded signed PDFs for long-term records.',
            ],
            [
                'question' => 'Does the audit trail show IP addresses?',
                'answer' => 'The workspace activity UI shows event types, recipient names, and timestamps — not IP addresses. Internal session data may exist for operations, but it is not presented as a user-facing audit field.',
            ],
        ],
        ],
        [
            'slug' => 'electronic-signature-legality',
            'updated_at' => '2026-08-08',
            'title' => 'Electronic Signature Legality',
            'excerpt' => 'General background on ESIGN, UETA, and eIDAS — plus honest limits on what CubSign guarantees.',
            'meta_title' => 'Are Electronic Signatures Legal? | CubSign',
            'meta_description' => 'Educational overview of electronic signature frameworks. CubSign provides signing tools and activity records — not legal advice or outcome guarantees.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'Are electronic signatures legally binding?',
                'answer' => 'Often yes under frameworks like ESIGN, UETA, and eIDAS when intent and consent requirements are met — but outcomes depend on document type and jurisdiction. This is not legal advice.',
            ],
            [
                'question' => 'What does CubSign provide?',
                'answer' => 'A browser signing workflow, applied signatures on PDFs, and workspace activity events. It does not provide qualified certificates or legal determinations.',
            ],
            [
                'question' => 'Documents that may need special handling?',
                'answer' => 'Wills, some real-estate transfers, notarized instruments, and regulated industries may require wet ink, witnesses, or specific platforms. Consult counsel.',
            ],
        ],
        ],
        [
            'slug' => 'troubleshooting-upload-errors',
            'updated_at' => '2026-08-08',
            'title' => 'Troubleshooting Upload Errors',
            'excerpt' => 'Fix common PDF upload failures, file type, size, network, and browser issues and get back to signing.',
            'meta_title' => 'Troubleshooting PDF Upload Errors | CubSign',
            'meta_description' => 'Work through common CubSign upload errors, invalid file type, size limits, network issues, and browser restrictions with clear fixes.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'Why does CubSign say my file is too large?',
                'answer' => 'The upload limit is 25 MB. Compress the PDF, lower scan resolution, or split it, then upload again. See Maximum Upload Size.',
            ],
            [
                'question' => 'I get an invalid file type error, what is wrong?',
                'answer' => 'The file is likely not a real PDF. Export or Save as PDF from your source app instead of renaming a Word or image file.',
            ],
            [
                'question' => 'My upload keeps failing with a network error. What now?',
                'answer' => 'Retry on a stable connection, disable VPN or ad blockers, and try a supported browser in a private window. If it persists, contact support with the details.',
            ],
        ],
        ],
        [
            'slug' => 'contact-support',
            'updated_at' => '2026-08-08',
            'title' => 'Contact Support',
            'excerpt' => 'Reach the CubSign team when you need help beyond the Help Center, and learn what details to include.',
            'meta_title' => 'How to Contact CubSign Support | CubSign',
            'meta_description' => 'Learn how to contact CubSign support, what details to include for a fast response, and how to help us reproduce your issue.',
            'author' => 'CubSign Product & Engineering Team',
            'faq' => [
            [
                'question' => 'How do I contact CubSign support?',
                'answer' => 'Email support@cubsign.com or use the Contact page. Include the error message, browser, device, and what you were trying to do.',
            ],
            [
                'question' => 'What details should I include in a support request?',
                'answer' => 'A short description of the problem, screenshots or the exact error, your browser and device, and whether you are signed in or a guest.',
            ],
            [
                'question' => 'How fast will I get a response?',
                'answer' => 'We respond as quickly as possible during Early Access. Providing clear details up front helps us resolve your issue faster.',
            ],
        ],
        ],
    ],

];
