<?php

/**
 * Help Center article metadata for server-side features (sitemap, etc.).
 * Keep slugs and updated_at in sync with resources/js/constants/help.js.
 * Generated by scripts/generate-help-content.mjs
 */
return [

    'articles' => [
        ['slug' => 'what-is-cubsign', 'updated_at' => '2026-08-08'],
        ['slug' => 'create-your-cubsign-account', 'updated_at' => '2026-08-08'],
        ['slug' => 'mobile-support', 'updated_at' => '2026-08-08'],
        ['slug' => 'browser-compatibility', 'updated_at' => '2026-08-08'],
        ['slug' => 'how-to-upload-a-pdf', 'updated_at' => '2026-08-08'],
        ['slug' => 'supported-file-types', 'updated_at' => '2026-08-08'],
        ['slug' => 'maximum-upload-size', 'updated_at' => '2026-08-08'],
        ['slug' => 'how-to-sign-a-pdf-online', 'updated_at' => '2026-08-08'],
        ['slug' => 'draw-vs-type-signature', 'updated_at' => '2026-08-08'],
        ['slug' => 'upload-your-signature-image', 'updated_at' => '2026-08-08'],
        ['slug' => 'download-signed-pdf', 'updated_at' => '2026-08-08'],
        ['slug' => 'share-documents', 'updated_at' => '2026-08-08'],
        ['slug' => 'delete-documents', 'updated_at' => '2026-08-08'],
        ['slug' => 'email-verification', 'updated_at' => '2026-08-08'],
        ['slug' => 'google-login', 'updated_at' => '2026-08-08'],
        ['slug' => 'reset-password', 'updated_at' => '2026-08-08'],
        ['slug' => 'secure-storage', 'updated_at' => '2026-08-08'],
        ['slug' => 'document-privacy', 'updated_at' => '2026-08-08'],
        ['slug' => 'audit-trail', 'updated_at' => '2026-08-08'],
        ['slug' => 'electronic-signature-legality', 'updated_at' => '2026-08-08'],
        ['slug' => 'troubleshooting-upload-errors', 'updated_at' => '2026-08-08'],
        ['slug' => 'contact-support', 'updated_at' => '2026-08-08'],
    ],

];
